### ISSUE TITLE
I met a error on win10, "Your configuration specifies to merge with the ref 'refs/heads/master' from the remote, but no such ref was fetched."

### ISSUE THREAD

**Issue by OrdinaryYZH** [CharlesChiuGit/Logseq-Git-Sync-101#13] opened 2022-10-25 08:39 UTC
I have done the step from this https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/wiki/For-Windows-users

but I don't konw what the tips said , I search on web , but can't fix it

![image](https://user-images.githubusercontent.com/10287222/197725959-56b1c3b4-0c23-4e1c-979d-5fee51934141.png)

**Comment by CharlesChiuGit** [comment] 2022-10-25 10:11
Can you use terminal to git pull and git push?

**Comment by OrdinaryYZH** [comment] 2022-10-25 14:42
I can pull and push by git bash or other GUI, and I try to edit the post-commit, git push origin main -> git push origin master，but the same problem, did I edit wrong?

my .git/config :
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
	safecrlf = false
[remote "origin"]
	url = xxxxxxxxxxxxx
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

and it's a private repo

**Comment by CharlesChiuGit** [comment] 2022-10-25 14:48
So your default branch is `master`, not `main` right?

Maybe try to pull your github repo and re-link your logseq to that newly-pulled folder? 
**PLEASE** backup your files before your do anything risky!! I would also recommand do a `clear cache` in logseq, maybe it would help.

**Comment by CharlesChiuGit** [comment] 2022-10-28 03:43
I assum u got things worked out, close it for now. Feel free to reopen it again.

**Closed by CharlesChiuGit** 2022-10-28 03:43 UTC

**Comment by CharlesChiuGit** [comment] 2023-03-22 01:01
@snorlaxjones hmmm, I can't reproduce it and it never happened to me on other git-related projects.

So if u do things from the terminal, everything will be fine?
